In [1]:
import pandas as pd
import os
from glob import glob
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Dense, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import json
import random

WARNING:tensorflow:From c:\Users\sigma\Documents\GitHub\ASE_2024\myenv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
directory_codeStructure = "D:\\ICSE_Dataset\\Derived_Features\\code_structure_feature_buggy_correct"
directory_embedding = "D:\\ICSE_Dataset\\Derived_Features\\embedding_features_buggy_correct"
directory_graph = "D:\\ICSE_Dataset\\Derived_Features\\graph_features_buggy_correct"

Label_1: Hyperparameter

In [16]:
#Embedding
def json_files_to_df(directory, label_keyword):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                with open(file_path, 'r') as f:
                    json_data = json.load(f)
                    data.append(json_data)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    df = pd.DataFrame(data)
    return df


df_hyperparameter_embedding = json_files_to_df(directory_embedding, 'Hyperparameter')
df_correct_embedding = json_files_to_df(directory_embedding, 'correct')
df_hyperparameter_embedding['label'] = 'Hyperparameter'
df_correct_embedding['label'] = 'correct'
min_count_embedding = min(len(df_hyperparameter_embedding), len(df_correct_embedding))
df_hyperparameter_embedding = df_hyperparameter_embedding.sample(n=min_count_embedding, random_state=1)
df_correct_embedding = df_correct_embedding.sample(n=min_count_embedding, random_state=1)
df_combined_embedding = pd.concat([df_hyperparameter_embedding, df_correct_embedding])
df_combined_embedding = df_combined_embedding.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_hyperparameter_embedding)} Hyperparameter files from embedding directory')
print(f'Selected {len(df_correct_embedding)} correct files from embedding directory')
print(f'Total combined data points from embedding directory: {len(df_combined_embedding)}')
df_combined_embedding.to_json('combined_embedding.json', orient='records')
print(df_combined_embedding)

Error decoding JSON from file D:\ICSE_Dataset\Derived_Features\embedding_features_buggy_correct\0_31556268_Hyperparameter_buggy.h5.json: Expecting value: line 1 column 1 (char 0)
Selected 4081 Hyperparameter files from embedding directory
Selected 4081 correct files from embedding directory
Total combined data points from embedding directory: 8162
                                 model_file  \
0     7657_68692047_Hyperparameter_buggy.h5
1                  3639_50481178_correct.h5
2     4523_71351646_Hyperparameter_buggy.h5
3                  3969_61553510_correct.h5
4      670_48934338_Hyperparameter_buggy.h5
...                                     ...
8157               1919_46642627_correct.h5
8158               1415_77416892_correct.h5
8159  4554_71351646_Hyperparameter_buggy.h5
8160  5707_73765263_Hyperparameter_buggy.h5
8161                453_68103873_correct.h5

                                              embedding           label
0     [0.16367369890213013, 0.23748232424259186, 0.0...  Hyperparameter
1     [0.18405327200889587, 0.2728056311607361, 0.10...         correct
2     [0.17668721079826355, 0.2513545751571655, 0.11...  Hyperparameter
3     [0.16761009395122528, 0.2628805637359619, 0.10...         correct
4     [0.1766625940799713, 0.2602795362472534, 0.078...  Hyperparameter
...                                                 ...             ...
8157  [0.19169928133487701, 0.2572789192199707, 0.09...         correct
8158  [0.16933181881904602, 0.2405780851840973, 0.11...         correct
8159  [0.17193560302257538, 0.25609657168388367, 0.1...  Hyperparameter
8160  [0.16586410999298096, 0.2581118941307068, 0.11...  Hyperparameter
8161  [0.1744520664215088, 0.20317330956459045, 0.11...         correct

[8162 rows x 3 columns]

In [18]:
labbeled_hyperparameter_embedding= df_combined_embedding.copy()
labbeled_hyperparameter_embedding.to_csv('labeled_hyperparameter_embedding.csv', index=False)

In [19]:
#graph
df_hyperparameter_graph = json_files_to_df(directory_graph, 'Hyperparameter')
df_correct_graph = json_files_to_df(directory_graph, 'correct')
df_hyperparameter_graph['label'] = 'Hyperparameter'
df_correct_graph['label'] = 'correct'
min_count_graph = min(len(df_hyperparameter_graph), len(df_correct_graph))
df_hyperparameter_graph = df_hyperparameter_graph.sample(n=min_count_graph, random_state=1)

df_correct_graph = df_correct_graph.sample(n=min_count_graph, random_state=1)
df_combined_graph = pd.concat([df_hyperparameter_graph, df_correct_graph])
df_combined_graph = df_combined_graph.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_hyperparameter_graph)} Hyperparameter files from graph directory')
print(f'Selected {len(df_correct_graph)} correct files from graph directory')
print(f'Total combined data points from graph directory: {len(df_combined_graph)}')

df_combined_graph.to_json('combined_graph.json', orient='records')
print(df_combined_graph)

labbeled_hyperparameter_graph= df_combined_graph.copy()
labbeled_hyperparameter_graph.to_csv('labeled_hyperparameter_graph.csv', index=False)

Selected 4081 Hyperparameter files from graph directory
Selected 4081 correct files from graph directory
Total combined data points from graph directory: 8162
                                      degree_centrality  \
0                                  {'0': 1.0, '1': 1.0}
1     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
2     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
3                                  {'0': 1.0, '1': 1.0}
4     {'0': 0.3333333333333333, '1': 0.6666666666666...
...                                                 ...
8157                     {'0': 0.5, '1': 1.0, '2': 0.5}
8158                     {'0': 0.5, '1': 1.0, '2': 0.5}
8159                               {'0': 1.0, '1': 1.0}
8160                               {'0': 1.0, '1': 1.0}
8161  {'0': 0.3333333333333333, '1': 0.6666666666666...

                                   closeness_centrality  \
0                                  {'0': 0.0, '1': 1.0}
1     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
2     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
3                                  {'0': 0.0, '1': 1.0}
4     {'0': 0.0, '1': 0.3333333333333333, '2': 0.444...
...                                                 ...
8157      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
8158      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
8159                               {'0': 0.0, '1': 1.0}
8160                               {'0': 0.0, '1': 1.0}
8161  {'0': 0.0, '1': 0.3333333333333333, '2': 0.444...

                                 betweenness_centrality  \
0                                  {'0': 0.0, '1': 0.0}
1     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
2     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
3                                  {'0': 0.0, '1': 0.0}
4     {'0': 0.0, '1': 0.3333333333333333, '2': 0.333...
...                                                 ...
8157                     {'0': 0.0, '1': 0.5, '2': 0.0}
8158                     {'0': 0.0, '1': 0.5, '2': 0.0}
8159                               {'0': 0.0, '1': 0.0}
8160                               {'0': 0.0, '1': 0.0}
8161  {'0': 0.0, '1': 0.3333333333333333, '2': 0.333...

                                                degree  transitivity  \
0                                     {'0': 1, '1': 1}             0
1     {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
2     {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
3                                     {'0': 1, '1': 1}             0
4                     {'0': 1, '1': 2, '2': 2, '3': 1}             0
...                                                ...           ...
8157                          {'0': 1, '1': 2, '2': 1}             0
8158                          {'0': 1, '1': 2, '2': 1}             0
8159                                  {'0': 1, '1': 1}             0
8160                                  {'0': 1, '1': 1}             0
8161                  {'0': 1, '1': 2, '2': 2, '3': 1}             0

                                   shortest_path_length  \
0                {'0': {'0': 0, '1': 1}, '1': {'1': 0}}
1     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
2     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
3                {'0': {'0': 0, '1': 1}, '1': {'1': 0}}
4     {'0': {'0': 0, '1': 1, '2': 2, '3': 3}, '1': {...
...                                                 ...
8157  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
8158  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
8159             {'0': {'0': 0, '1': 1}, '1': {'1': 0}}
8160             {'0': {'0': 0, '1': 1}, '1': {'1': 0}}
8161  {'0': {'0': 0, '1': 1, '2': 2, '3': 3}, '1': {...

                                 eigenvector_centrality  \
0     {'0': 0.001410435832630306, '1': 0.99999900533...
1     {'0': 1.800995096925549e-13, '1': 1.6641194695...
2     {'0': 1.800995096925549e-13, '1': 1.6641194695...
3     {'0': 0.001410435832630306, '1': 0.99999900533...
4     {'0': 9.080114753549862e-09, '1': 7.9178600650...
...                                                 ...
8157  {'0': 2.9780340102584615e-06, '1': 0.002441987...
8158  {'0': 2.9780340102584615e-06, '1': 0.002441987...
8159  {'0': 0.001410435832630306, '1': 0.99999900533...
8160  {'0': 0.001410435832630306, '1': 0.99999900533...
8161  {'0': 9.080114753549862e-09, '1': 7.9178600650...

                                               pagerank  \
0     {'0': 0.3508773619358619, '1': 0.649122638064138}
1     {'0': 0.0607158048829909, '1': 0.1123242344582...
2     {'0': 0.0607158048829909, '1': 0.1123242344582...
3     {'0': 0.3508773619358619, '1': 0.649122638064138}
4     {'0': 0.11615558155321364, '1': 0.214887855207...
...                                                 ...
8157  {'0': 0.1844167633067642, '1': 0.3411716203526...
8158  {'0': 0.1844167633067642, '1': 0.3411716203526...
8159  {'0': 0.3508773619358619, '1': 0.649122638064138}
8160  {'0': 0.3508773619358619, '1': 0.649122638064138}
8161  {'0': 0.11615558155321364, '1': 0.214887855207...

                                                   hubs  \
0                                  {'0': 1.0, '1': 0.0}
1     {'0': 0.9783551287573491, '1': -0.006167686523...
2     {'0': 0.11143060811761465, '1': 0.480045238476...
3                                  {'0': 1.0, '1': 0.0}
4     {'0': -1.0243371381948398, '1': 1.295021810905...
...                                                 ...
8157  {'0': 0.6673223839240217, '1': 0.3326776160759...
8158  {'0': 1.0107604372904642, '1': -0.010760437290...
8159                               {'0': 1.0, '1': 0.0}
8160                              {'0': 1.0, '1': -0.0}
8161  {'0': -0.1668426697195597, '1': 0.366842669719...

                                            authorities  \
0                                  {'0': 0.0, '1': 1.0}
1     {'0': -0.0, '1': 0.9783551287573491, '2': -0.0...
2     {'0': -0.0, '1': 0.11143060811761465, '2': 0.4...
3                                  {'0': 0.0, '1': 1.0}
4     {'0': -0.0, '1': -1.0243371381948398, '2': 1.2...
...                                                 ...
8157  {'0': -0.0, '1': 0.6673223839240217, '2': 0.33...
8158  {'0': -0.0, '1': 1.0107604372904642, '2': -0.0...
8159  {'0': -2.2204460492503136e-16, '1': 1.00000000...
8160                              {'0': -0.0, '1': 1.0}
8161  {'0': -0.0, '1': -0.1668426697195597, '2': 0.3...

                                                k_core   density  \
0                                     {'0': 1, '1': 1}  0.500000
1     {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667
2     {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667
3                                     {'0': 1, '1': 1}  0.500000
4                     {'0': 1, '1': 1, '2': 1, '3': 1}  0.250000
...                                                ...       ...
8157                          {'0': 1, '1': 1, '2': 1}  0.333333
8158                          {'0': 1, '1': 1, '2': 1}  0.333333
8159                                  {'0': 1, '1': 1}  0.500000
8160                                  {'0': 1, '1': 1}  0.500000
8161                  {'0': 1, '1': 1, '2': 1, '3': 1}  0.250000

               label
0     Hyperparameter
1            correct
2     Hyperparameter
3            correct
4     Hyperparameter
...              ...
8157         correct
8158         correct
8159  Hyperparameter
8160  Hyperparameter
8161         correct

[8162 rows x 13 columns]

In [3]:
import os
import json
import pandas as pd

def read_and_transpose_json(file_path):
    with open(file_path, 'r') as f:
        json_data = [json.loads(line) for line in f]
    df = pd.DataFrame(json_data).T 
    return df

def process_directory(directory, label_keyword):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_and_transpose_json(file_path)
                df_flat = df.values.flatten()  
                data.append(df_flat)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return pd.DataFrame(data)


directory_codeStructure = "D:\\ICSE_Dataset\\Derived_Features\\code_structure_feature_buggy_correct"
directory_embedding = "D:\\ICSE_Dataset\\Derived_Features\\embedding_feature_buggy_correct"
directory_graph = "D:\\ICSE_Dataset\\Derived_Features\\graph_feature_buggy_correct"
df_hyperparameter_codeStructure = process_directory(directory_codeStructure, 'Hyperparameter')
df_correct_codeStructure = process_directory(directory_codeStructure, 'correct')
df_hyperparameter_codeStructure['label'] = 'Hyperparameter'
df_correct_codeStructure['label'] = 'correct'
df_combined_codeStructure = pd.concat([df_hyperparameter_codeStructure, df_correct_codeStructure])
df_combined_codeStructure = df_combined_codeStructure.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Total combined data points from code structure directory: {len(df_combined_codeStructure)}')
df_combined_codeStructure.to_json('labeled_hyperparameter_codeStructure.json', orient='records')
print(df_combined_codeStructure)
labeled_hyperparameter_codeStructure = df_combined_codeStructure.copy()
labeled_hyperparameter_codeStructure.to_csv('labeled_hyperparameter_codeStructure.csv', index=False)

Total combined data points from code structure directory: 8289
             0          1              2             3           4    \
0     InputLayer       LSTM           LSTM  RepeatVector        LSTM
1     InputLayer       LSTM          Dense         Dense           0
2     InputLayer     Conv2D     Activation        Conv2D  Activation
3     InputLayer       LSTM          Dense             0           1
4     InputLayer      Dense          Dense         Dense           0
...          ...        ...            ...           ...         ...
8284  InputLayer       LSTM           LSTM         Dense           0
8285  InputLayer      Dense          Dense         Dense           0
8286  InputLayer  Embedding  Bidirectional         Dense     Dropout
8287  InputLayer      Dense          Dense             0           1
8288  InputLayer      Dense          Dense       Dropout       Dense

               5                6           7           8           9    ...  \
0             LSTM  TimeDistributed           0           1           2  ...
1                1                2           3        None  InputLayer  ...
2     MaxPooling2D          Flatten       Dense  Activation       Dense  ...
3                2             None  InputLayer        LSTM        LSTM  ...
4                1                2           3        None  InputLayer  ...
...            ...              ...         ...         ...         ...  ...
8284             1                2           3        None  InputLayer  ...
8285             1                2           3        None  InputLayer  ...
8286         Dense                0           1           2           3  ...
8287             2             None  InputLayer       Dense       Dense  ...
8288       Dropout            Dense     Dropout       Dense     Dropout  ...

       278   279   280   281   282   283   284   285   286   287
0     None  None  None  None  None  None  None  None  None  None
1     None  None  None  None  None  None  None  None  None  None
2     None  None  None  None  None  None  None  None  None  None
3      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4     None  None  None  None  None  None  None  None  None  None
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
8284   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
8285  None  None  None  None  None  None  None  None  None  None
8286   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
8287  None  None  None  None  None  None  None  None  None  None
8288   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[8289 rows x 289 columns]

In [4]:
labeled_hyperparameter_codeStructure

,0,1,2,3,4,5,6,7,8,9,...,278,279,280,281,282,283,284,285,286,287
0,InputLayer,LSTM,LSTM,RepeatVector,LSTM,LSTM,TimeDistributed,0,1,2,...,None,None,None,None,None,None,None,None,None,None
1,InputLayer,LSTM,Dense,Dense,0,1,2,3,None,InputLayer,...,None,None,None,None,None,None,None,None,None,None
2,InputLayer,Conv2D,Activation,Conv2D,Activation,MaxPooling2D,Flatten,Dense,Activation,Dense,...,None,None,None,None,None,None,None,None,None,None
3,InputLayer,LSTM,Dense,0,1,2,None,InputLayer,LSTM,LSTM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,InputLayer,Dense,Dense,Dense,0,1,2,3,None,InputLayer,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8284,InputLayer,LSTM,LSTM,Dense,0,1,2,3,None,InputLayer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8285,InputLayer,Dense,Dense,Dense,0,1,2,3,None,InputLayer,...,None,None,None,None,None,None,None,None,None,None
8286,InputLayer,Embedding,Bidirectional,Dense,Dropout,Dense,0,1,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8287,InputLayer,Dense,Dense,0,1,2,None,InputLayer,Dense,Dense,...,None,None,None,None,None,None,None,None,None,None
8288,InputLayer,Dense,Dense,Dropout,Dense,Dropout,Dense,Dropout,Dense,Dropout,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
def read_json(file_path):
    with open(file_path, 'r') as f:
        json_data = [json.loads(line) for line in f]
    df = pd.DataFrame(json_data)
    return df

def determine_max_rows(directory, label_keyword):
    max_rows = 0
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                max_rows = max(max_rows, len(df))
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return max_rows
def process_directory(directory, label_keyword, max_rows):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                current_rows = len(df)
                if current_rows < max_rows:
                    padding = pd.DataFrame([{}] * (max_rows - current_rows))
                    df = pd.concat([df, padding], ignore_index=True)
                df_flat = df.values.flatten() 
                data.append(df_flat)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return pd.DataFrame(data)

max_rows_codeStructure = determine_max_rows(directory_codeStructure, 'Hyperparameter')
max_rows_codeStructure = max(max_rows_codeStructure, determine_max_rows(directory_codeStructure, 'correct'))
print(f'Maximum number of rows for padding: {max_rows_codeStructure}')
df_hyperparameter_codeStructure = process_directory(directory_codeStructure, 'Hyperparameter', max_rows_codeStructure)
df_correct_codeStructure = process_directory(directory_codeStructure, 'correct', max_rows_codeStructure)
df_hyperparameter_codeStructure['label'] = 'Hyperparameter'
df_correct_codeStructure['label'] = 'correct'

df_combined_codeStructure = pd.concat([df_hyperparameter_codeStructure, df_correct_codeStructure])
df_combined_codeStructure = df_combined_codeStructure.sample(frac=1, random_state=1).reset_index(drop=True)

print(f'Total combined data points from code structure directory: {len(df_combined_codeStructure)}')
df_combined_codeStructure.to_json('labeled_hyperparameter_codeStructure.json', orient='records')
print(df_combined_codeStructure)
labeled_hyperparameter_codeStructure_padded = df_combined_codeStructure.copy()
labeled_hyperparameter_codeStructure_padded.to_csv('labeled_hyperparameter_codeStructure_padding.csv', index=False)

Maximum number of rows for padding: 24
Total combined data points from code structure directory: 8289
               0    1     2          3     4     5     6                    7  \
0     InputLayer  0.0  None       LSTM  None  None  None        [None, 10, 5]
1     InputLayer  0.0  None       LSTM  None  None  None         [None, 2, 2]
2     InputLayer  0.0  None     Conv2D  None  None  None  [None, 100, 100, 1]
3     InputLayer  0.0  None       LSTM  None  None  None     [None, 10000, 1]
4     InputLayer  0.0  None      Dense  None  None  None          [None, 784]
...          ...  ...   ...        ...   ...   ...   ...                  ...
8284  InputLayer  0.0  None       LSTM  None  None  None         [None, 1, 1]
8285  InputLayer  0.0  None      Dense  None  None  None            [None, 2]
8286  InputLayer  0.0  None  Embedding  None  None  None           [None, 30]
8287  InputLayer  0.0  None      Dense  None  None  None            [None, 2]
8288  InputLayer  0.0  None      Dense  None  None  None           [None, 12]

                       8      9  ...  279  280  281  282 283 284 285 286 287  \
0          [None, 10, 8]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
1            [None, 100]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
2     [None, 98, 98, 32]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
3             [None, 50]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
4            [None, 784]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
...                  ...    ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..
8284       [None, 1, 64]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
8285           [None, 2]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
8286     [None, 30, 300]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
8287           [None, 2]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
8288          [None, 32]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN

               label
0            correct
1            correct
2            correct
3     Hyperparameter
4            correct
...              ...
8284  Hyperparameter
8285         correct
8286  Hyperparameter
8287         correct
8288  Hyperparameter

[8289 rows x 289 columns]

In [6]:
labeled_hyperparameter_codeStructure_padded

,0,1,2,3,4,5,6,7,8,9,...,279,280,281,282,283,284,285,286,287,label
0,InputLayer,0.0,None,LSTM,None,None,None,"[None, 10, 5]","[None, 10, 8]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct
1,InputLayer,0.0,None,LSTM,None,None,None,"[None, 2, 2]","[None, 100]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct
2,InputLayer,0.0,None,Conv2D,None,None,None,"[None, 100, 100, 1]","[None, 98, 98, 32]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct
3,InputLayer,0.0,None,LSTM,None,None,None,"[None, 10000, 1]","[None, 50]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyperparameter
4,InputLayer,0.0,None,Dense,None,None,None,"[None, 784]","[None, 784]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8284,InputLayer,0.0,None,LSTM,None,None,None,"[None, 1, 1]","[None, 1, 64]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyperparameter
8285,InputLayer,0.0,None,Dense,None,None,None,"[None, 2]","[None, 2]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct
8286,InputLayer,0.0,None,Embedding,None,None,None,"[None, 30]","[None, 30, 300]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyperparameter
8287,InputLayer,0.0,None,Dense,None,None,None,"[None, 2]","[None, 2]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,correct
8288,InputLayer,0.0,None,Dense,None,None,None,"[None, 12]","[None, 32]",False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Hyperparameter

In [7]:
# print one row of the dataframe
print(labeled_hyperparameter_codeStructure_padded.iloc[0])

0        InputLayer
1               0.0
2              None
3              LSTM
4              None
            ...
284             NaN
285             NaN
286             NaN
287             NaN
label       correct
Name: 0, Length: 289, dtype: object

Label 2: Layer

In [3]:
#Embedding
def json_files_to_df(directory, label_keyword):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                with open(file_path, 'r') as f:
                    json_data = json.load(f)
                    data.append(json_data)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    df = pd.DataFrame(data)
    return df


df_Layer_embedding = json_files_to_df(directory_embedding, 'Layer')
df_correct_embedding = json_files_to_df(directory_embedding, 'correct')
df_Layer_embedding['label'] = 'Layer'
df_correct_embedding['label'] = 'correct'
min_count_embedding = min(len(df_Layer_embedding), len(df_correct_embedding))
df_Layer_embedding = df_Layer_embedding.sample(n=min_count_embedding, random_state=1)
df_correct_embedding = df_correct_embedding.sample(n=min_count_embedding, random_state=1)
df_combined_embedding = pd.concat([df_Layer_embedding, df_correct_embedding])
df_combined_embedding = df_combined_embedding.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Layer_embedding)} Layer files from embedding directory')
print(f'Selected {len(df_correct_embedding)} correct files from embedding directory')
print(f'Total combined data points from embedding directory: {len(df_combined_embedding)}')
df_combined_embedding.to_json('combined_embedding.json', orient='records')
print(df_combined_embedding)
labbeled_Layer_embedding= df_combined_embedding.copy()
labbeled_Layer_embedding.to_csv('labeled_Layer_embedding.csv', index=False)

#Graph
df_Layer_graph = json_files_to_df(directory_graph, 'Layer')
df_correct_graph = json_files_to_df(directory_graph, 'correct')
df_Layer_graph['label'] = 'Layer'
df_correct_graph['label'] = 'correct'
min_count_graph = min(len(df_Layer_graph), len(df_correct_graph))
df_Layer_graph = df_Layer_graph.sample(n=min_count_graph, random_state=1)

df_correct_graph = df_correct_graph.sample(n=min_count_graph, random_state=1)
df_combined_graph = pd.concat([df_Layer_graph, df_correct_graph])
df_combined_graph = df_combined_graph.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Layer_graph)} Layer files from graph directory')
print(f'Selected {len(df_correct_graph)} correct files from graph directory')
print(f'Total combined data points from graph directory: {len(df_combined_graph)}')

df_combined_graph.to_json('combined_graph.json', orient='records')
print(df_combined_graph)

labbeled_Layer_graph= df_combined_graph.copy()
labbeled_Layer_graph.to_csv('labeled_Layer_graph.csv', index=False)

#Code Structure
def read_json(file_path):
    with open(file_path, 'r') as f:
        json_data = [json.loads(line) for line in f]
    df = pd.DataFrame(json_data)
    return df

def determine_max_rows(directory, label_keyword):
    max_rows = 0
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                max_rows = max(max_rows, len(df))
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return max_rows
def process_directory(directory, label_keyword, max_rows):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                current_rows = len(df)
                if current_rows < max_rows:
                    padding = pd.DataFrame([{}] * (max_rows - current_rows))
                    df = pd.concat([df, padding], ignore_index=True)
                df_flat = df.values.flatten() 
                data.append(df_flat)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return pd.DataFrame(data)

max_rows_codeStructure = determine_max_rows(directory_codeStructure, 'Layer')
max_rows_codeStructure = max(max_rows_codeStructure, determine_max_rows(directory_codeStructure, 'correct'))
print(f'Maximum number of rows for padding: {max_rows_codeStructure}')
df_Layer_codeStructure = process_directory(directory_codeStructure, 'Layer', max_rows_codeStructure)
df_correct_codeStructure = process_directory(directory_codeStructure, 'correct', max_rows_codeStructure)
df_Layer_codeStructure['label'] = 'Layer'
df_correct_codeStructure['label'] = 'correct'

df_combined_codeStructure = pd.concat([df_Layer_codeStructure, df_correct_codeStructure])
df_combined_codeStructure = df_combined_codeStructure.sample(frac=1, random_state=1).reset_index(drop=True)

print(f'Total combined data points from code structure directory: {len(df_combined_codeStructure)}')
df_combined_codeStructure.to_json('labeled_Layer_codeStructure.json', orient='records')
print(df_combined_codeStructure)
labeled_Layer_codeStructure_padded = df_combined_codeStructure.copy()
labeled_Layer_codeStructure_padded.to_csv('labeled_Layer_codeStructure_padding.csv', index=False)

Selected 1371 Layer files from embedding directory
Selected 1371 correct files from embedding directory
Total combined data points from embedding directory: 2742
                        model_file  \
0         3695_73765263_correct.h5
1     5167_72328867_Layer_buggy.h5
2     3259_46642627_Layer_buggy.h5
3          892_70848143_correct.h5
4      545_50481178_Layer_buggy.h5
...                            ...
2737  3916_66840108_Layer_buggy.h5
2738  2566_77416892_Layer_buggy.h5
2739   265_44164749_Layer_buggy.h5
2740  5319_73146829_Layer_buggy.h5
2741  1982_70848143_Layer_buggy.h5

                                              embedding    label
0     [0.1762203425168991, 0.2688315808773041, 0.105...  correct
1     [0.12099839746952057, 0.23035728931427002, 0.0...    Layer
2     [0.18868303298950195, 0.25621867179870605, 0.0...    Layer
3     [0.1630043089389801, 0.23289208114147186, 0.08...  correct
4     [0.18807436525821686, 0.2614184021949768, 0.09...    Layer
...                                                 ...      ...
2737  [0.1836426854133606, 0.2568027079105377, 0.091...    Layer
2738  [0.17265352606773376, 0.2514723241329193, 0.11...    Layer
2739  [0.17409014701843262, 0.24849480390548706, 0.0...    Layer
2740  [0.15595442056655884, 0.2503541111946106, 0.07...    Layer
2741  [0.16685254871845245, 0.23447377979755402, 0.0...    Layer

[2742 rows x 3 columns]
Selected 1371 Layer files from graph directory
Selected 1371 correct files from graph directory
Total combined data points from graph directory: 2742
                                      degree_centrality  \
0     {'0': 0.3333333333333333, '1': 0.6666666666666...
1     {'0': 0.16666666666666666, '1': 0.333333333333...
2                        {'0': 0.5, '1': 1.0, '2': 0.5}
3                        {'0': 0.5, '1': 1.0, '2': 0.5}
4     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
...                                                 ...
2737                     {'0': 0.5, '1': 1.0, '2': 0.5}
2738                     {'0': 0.5, '1': 1.0, '2': 0.5}
2739  {'0': 0.25, '1': 0.5, '2': 0.5, '3': 0.5, '4':...
2740  {'0': 0.07692307692307693, '1': 0.153846153846...
2741                     {'0': 0.5, '1': 1.0, '2': 0.5}

                                   closeness_centrality  \
0     {'0': 0.0, '1': 0.3333333333333333, '2': 0.444...
1     {'0': 0.0, '1': 0.16666666666666666, '2': 0.22...
2         {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
3         {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
4     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
...                                                 ...
2737      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
2738      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
2739  {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
2740  {'0': 0.0, '1': 0.07692307692307693, '2': 0.10...
2741      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}

                                 betweenness_centrality  \
0     {'0': 0.0, '1': 0.3333333333333333, '2': 0.333...
1     {'0': 0.0, '1': 0.16666666666666666, '2': 0.26...
2                        {'0': 0.0, '1': 0.5, '2': 0.0}
3                        {'0': 0.0, '1': 0.5, '2': 0.0}
4     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
...                                                 ...
2737                     {'0': 0.0, '1': 0.5, '2': 0.0}
2738                     {'0': 0.0, '1': 0.5, '2': 0.0}
2739  {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
2740  {'0': 0.0, '1': 0.07692307692307693, '2': 0.14...
2741                     {'0': 0.0, '1': 0.5, '2': 0.0}

                                                 degree  transitivity  \
0                      {'0': 1, '1': 2, '2': 2, '3': 1}             0
1     {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
2                              {'0': 1, '1': 2, '2': 1}             0
3                              {'0': 1, '1': 2, '2': 1}             0
4      {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
...                                                 ...           ...
2737                           {'0': 1, '1': 2, '2': 1}             0
2738                           {'0': 1, '1': 2, '2': 1}             0
2739           {'0': 1, '1': 2, '2': 2, '3': 2, '4': 1}             0
2740  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
2741                           {'0': 1, '1': 2, '2': 1}             0

                                   shortest_path_length  \
0     {'0': {'0': 0, '1': 1, '2': 2, '3': 3}, '1': {...
1     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
2     {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
3     {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
4     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
...                                                 ...
2737  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
2738  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
2739  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}...
2740  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
2741  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...

                                 eigenvector_centrality  \
0     {'0': 9.080114753549862e-09, '1': 7.9178600650...
1     {'0': 1.0604381234672364e-15, '1': 9.968118360...
2     {'0': 2.9780340102584615e-06, '1': 0.002441987...
3     {'0': 2.9780340102584615e-06, '1': 0.002441987...
4     {'0': 1.800995096925549e-13, '1': 1.6641194695...
...                                                 ...
2737  {'0': 2.9780340102584615e-06, '1': 0.002441987...
2738  {'0': 2.9780340102584615e-06, '1': 0.002441987...
2739  {'0': 3.63361523133218e-11, '1': 3.28115455389...
2740  {'0': 7.188874596576391e-30, '1': 7.1529302235...
2741  {'0': 2.9780340102584615e-06, '1': 0.002441987...

                                               pagerank  \
0     {'0': 0.11615558155321364, '1': 0.214887855207...
1     {'0': 0.04762025246977224, '1': 0.088097655544...
2     {'0': 0.1844167633067642, '1': 0.3411716203526...
3     {'0': 0.1844167633067642, '1': 0.3411716203526...
4     {'0': 0.0607158048829909, '1': 0.1123242344582...
...                                                 ...
2737  {'0': 0.1844167633067642, '1': 0.3411716203526...
2738  {'0': 0.1844167633067642, '1': 0.3411716203526...
2739  {'0': 0.08118382772690558, '1': 0.150189066098...
2740  {'0': 0.016824171213993835, '1': 0.03112456762...
2741  {'0': 0.1844167633067642, '1': 0.3411716203526...

                                                   hubs  \
0     {'0': 0.29580073253416467, '1': 0.453602572684...
1     {'0': 0.011864557757521552, '1': -0.3743218677...
2     {'0': -0.25077277440668927, '1': 1.25077277440...
3     {'0': 0.8429098611524486, '1': 0.1570901388475...
4     {'0': 0.06214867734524601, '1': -0.28016407307...
...                                                 ...
2737  {'0': 0.4078561846151954, '1': 0.5921438153848...
2738  {'0': -1.2166272454301565, '1': 2.216627245430...
2739  {'0': -0.4446678846557302, '1': 0.0, '2': 1.58...
2740  {'0': 0.38372044639850333, '1': -0.21124879050...
2741  {'0': -0.7185989164258655, '1': 1.718598916425...

                                            authorities  \
0     {'0': -1.3249423544937297e-16, '1': 0.29580073...
1     {'0': -0.0, '1': 0.011864557757521552, '2': -0...
2     {'0': 0.0, '1': -0.25077277440668927, '2': 1.2...
3     {'0': 0.0, '1': 0.8429098611524486, '2': 0.157...
4     {'0': 0.0, '1': 0.06214867734524601, '2': -0.2...
...                                                 ...
2737  {'0': 0.0, '1': 0.4078561846151954, '2': 0.592...
2738  {'0': 5.614532171350093e-16, '1': -1.216627245...
2739  {'0': 0.0, '1': -0.4446678846557302, '2': 0.0,...
2740  {'0': 0.0, '1': 0.38372044639850333, '2': -0.2...
2741  {'0': 4.136212808324567e-16, '1': -0.718598916...

                                                 k_core   density    label
0                      {'0': 1, '1': 1, '2': 1, '3': 1}  0.250000  correct
1     {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.142857    Layer
2                              {'0': 1, '1': 1, '2': 1}  0.333333    Layer
3                              {'0': 1, '1': 1, '2': 1}  0.333333  correct
4      {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667    Layer
...                                                 ...       ...      ...
2737                           {'0': 1, '1': 1, '2': 1}  0.333333    Layer
2738                           {'0': 1, '1': 1, '2': 1}  0.333333    Layer
2739           {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}  0.200000    Layer
2740  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.071429    Layer
2741                           {'0': 1, '1': 1, '2': 1}  0.333333    Layer

[2742 rows x 13 columns]
Maximum number of rows for padding: 24
Total combined data points from code structure directory: 5452
               0    1     2              3     4               5            6  \
0     InputLayer  0.0  None           LSTM  None            None         None
1     InputLayer  0.0  None  Bidirectional  None  [None, 11, 12]  [None, 150]
2     InputLayer  0.0  None      Embedding  None            None         None
3     InputLayer  0.0  None         Conv2D  None            None         None
4     InputLayer  0.0  None          Dense  None            None         None
...          ...  ...   ...            ...   ...             ...          ...
5447  InputLayer  0.0  None          Dense  None            None         None
5448  InputLayer  0.0  None      Embedding  None            None         None
5449  InputLayer  0.0  None           LSTM  None            None         None
5450  InputLayer  0.0  None         Conv2D  None            None         None
5451  InputLayer  0.0  None          Dense  None            None         None

                      7                   8          9  ...   279   280   281  \
0        [None, 150, 1]    [None, 150, 100]      False  ...   NaN   NaN   NaN
1                 False           [12, 300]  [75, 300]  ...  None  None  None
2           [None, 500]    [None, 500, 128]      False  ...   NaN   NaN   NaN
3     [None, 64, 64, 3]  [None, 64, 64, 64]      False  ...   NaN   NaN   NaN
4             [None, 2]         [None, 196]      False  ...   NaN   NaN   NaN
...                 ...                 ...        ...  ...   ...   ...   ...
5447        [None, 784]         [None, 392]      False  ...   NaN   NaN   NaN
5448        [None, 300]    [None, 300, 100]      False  ...   NaN   NaN   NaN
5449      [None, 5, 18]       [None, 5, 50]      False  ...   NaN   NaN   NaN
5450  [None, 64, 64, 3]  [None, 64, 64, 64]      False  ...   NaN   NaN   NaN
5451          [None, 2]           [None, 2]      False  ...   NaN   NaN   NaN

       282 283 284 285 286 287    label
0      NaN NaN NaN NaN NaN NaN  correct
1     None NaN NaN NaN NaN NaN    Layer
2      NaN NaN NaN NaN NaN NaN  correct
3      NaN NaN NaN NaN NaN NaN  correct
4      NaN NaN NaN NaN NaN NaN    Layer
...    ...  ..  ..  ..  ..  ..      ...
5447   NaN NaN NaN NaN NaN NaN    Layer
5448   NaN NaN NaN NaN NaN NaN  correct
5449   NaN NaN NaN NaN NaN NaN  correct
5450   NaN NaN NaN NaN NaN NaN    Layer
5451   NaN NaN NaN NaN NaN NaN  correct

[5452 rows x 289 columns]

Label 3: Optimization

In [4]:
def json_files_to_df(directory, label_keyword):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                with open(file_path, 'r') as f:
                    json_data = json.load(f)
                    data.append(json_data)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    df = pd.DataFrame(data)
    return df

# Embedding
df_Optimization_embedding = json_files_to_df(directory_embedding, 'Optimization')
df_correct_embedding = json_files_to_df(directory_embedding, 'correct')
df_Optimization_embedding['label'] = 'Optimization'
df_correct_embedding['label'] = 'correct'
min_count_embedding = min(len(df_Optimization_embedding), len(df_correct_embedding))
df_Optimization_embedding = df_Optimization_embedding.sample(n=min_count_embedding, random_state=1)
df_correct_embedding = df_correct_embedding.sample(n=min_count_embedding, random_state=1)
df_combined_embedding = pd.concat([df_Optimization_embedding, df_correct_embedding])
df_combined_embedding = df_combined_embedding.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Optimization_embedding)} Optimization files from embedding directory')
print(f'Selected {len(df_correct_embedding)} correct files from embedding directory')
print(f'Total combined data points from embedding directory: {len(df_combined_embedding)}')
df_combined_embedding.to_json('combined_embedding.json', orient='records')
print(df_combined_embedding)
labeled_Optimization_embedding = df_combined_embedding.copy()
labeled_Optimization_embedding.to_csv('labeled_Optimization_embedding.csv', index=False)

# Graph
df_Optimization_graph = json_files_to_df(directory_graph, 'Optimization')
df_correct_graph = json_files_to_df(directory_graph, 'correct')
df_Optimization_graph['label'] = 'Optimization'
df_correct_graph['label'] = 'correct'
min_count_graph = min(len(df_Optimization_graph), len(df_correct_graph))
df_Optimization_graph = df_Optimization_graph.sample(n=min_count_graph, random_state=1)
df_correct_graph = df_correct_graph.sample(n=min_count_graph, random_state=1)
df_combined_graph = pd.concat([df_Optimization_graph, df_correct_graph])
df_combined_graph = df_combined_graph.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Optimization_graph)} Optimization files from graph directory')
print(f'Selected {len(df_correct_graph)} correct files from graph directory')
print(f'Total combined data points from graph directory: {len(df_combined_graph)}')
df_combined_graph.to_json('combined_graph.json', orient='records')
print(df_combined_graph)
labeled_Optimization_graph = df_combined_graph.copy()
labeled_Optimization_graph.to_csv('labeled_Optimization_graph.csv', index=False)

# Code Structure
def read_json(file_path):
    with open(file_path, 'r') as f:
        json_data = [json.loads(line) for line in f]
    df = pd.DataFrame(json_data)
    return df

def determine_max_rows(directory, label_keyword):
    max_rows = 0;
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                max_rows = max(max_rows, len(df))
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return max_rows

def process_directory(directory, label_keyword, max_rows):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                current_rows = len(df)
                if current_rows < max_rows:
                    padding = pd.DataFrame([{}] * (max_rows - current_rows))
                    df = pd.concat([df, padding], ignore_index=True)
                df_flat = df.values.flatten() 
                data.append(df_flat)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return pd.DataFrame(data)

max_rows_codeStructure = determine_max_rows(directory_codeStructure, 'Optimization')
max_rows_codeStructure = max(max_rows_codeStructure, determine_max_rows(directory_codeStructure, 'correct'))
print(f'Maximum number of rows for padding: {max_rows_codeStructure}')
df_Optimization_codeStructure = process_directory(directory_codeStructure, 'Optimization', max_rows_codeStructure)
df_correct_codeStructure = process_directory(directory_codeStructure, 'correct', max_rows_codeStructure)
df_Optimization_codeStructure['label'] = 'Optimization'
df_correct_codeStructure['label'] = 'correct'

df_combined_codeStructure = pd.concat([df_Optimization_codeStructure, df_correct_codeStructure])
df_combined_codeStructure = df_combined_codeStructure.sample(frac=1, random_state=1).reset_index(drop=True)

print(f'Total combined data points from code structure directory: {len(df_combined_codeStructure)}')
df_combined_codeStructure.to_json('labeled_Optimization_codeStructure.json', orient='records')
print(df_combined_codeStructure)
labeled_Optimization_codeStructure_padded = df_combined_codeStructure.copy()
labeled_Optimization_codeStructure_padded.to_csv('labeled_Optimization_codeStructure_padding.csv', index=False)

Selected 1239 Optimization files from embedding directory
Selected 1239 correct files from embedding directory
Total combined data points from embedding directory: 2478
                               model_file  \
0                1997_50481178_correct.h5
1                2055_52782432_correct.h5
2                2130_59325381_correct.h5
3     7847_37624102_Optimization_buggy.h5
4                2396_48934338_correct.h5
...                                   ...
2473  3249_31556268_Optimization_buggy.h5
2474  2585_67727890_Optimization_buggy.h5
2475  6251_77416892_Optimization_buggy.h5
2476  6882_70178206_Optimization_buggy.h5
2477  7852_37624102_Optimization_buggy.h5

                                              embedding         label
0     [0.19117514789104462, 0.25849002599716187, 0.1...       correct
1     [0.1671713888645172, 0.2590924799442291, 0.114...       correct
2     [0.14262327551841736, 0.2287479043006897, 0.09...       correct
3     [0.15423692762851715, 0.2485947161912918, 0.10...  Optimization
4     [0.18001976609230042, 0.25672391057014465, 0.0...       correct
...                                                 ...           ...
2473  [0.17181628942489624, 0.2503044605255127, 0.09...  Optimization
2474  [0.16196605563163757, 0.2567674219608307, 0.10...  Optimization
2475  [0.16313791275024414, 0.24937695264816284, 0.1...  Optimization
2476  [0.14948514103889465, 0.22375932335853577, 0.0...  Optimization
2477  [0.157301127910614, 0.24433499574661255, 0.102...  Optimization

[2478 rows x 3 columns]
Selected 1239 Optimization files from graph directory
Selected 1239 correct files from graph directory
Total combined data points from graph directory: 2478
                                      degree_centrality  \
0     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
1     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
2     {'0': 0.16666666666666666, '1': 0.333333333333...
3     {'0': 0.1111111111111111, '1': 0.2222222222222...
4                        {'0': 0.5, '1': 1.0, '2': 0.5}
...                                                 ...
2473  {'0': 0.3333333333333333, '1': 0.6666666666666...
2474  {'0': 0.1, '1': 0.2, '2': 0.2, '3': 0.2, '4': ...
2475                     {'0': 0.5, '1': 1.0, '2': 0.5}
2476  {'0': 0.25, '1': 0.5, '2': 0.5, '3': 0.5, '4':...
2477  {'0': 0.1111111111111111, '1': 0.2222222222222...

                                   closeness_centrality  \
0     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
1     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
2     {'0': 0.0, '1': 0.16666666666666666, '2': 0.22...
3     {'0': 0.0, '1': 0.1111111111111111, '2': 0.148...
4         {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
...                                                 ...
2473  {'0': 0.0, '1': 0.3333333333333333, '2': 0.444...
2474  {'0': 0.0, '1': 0.1, '2': 0.13333333333333333,...
2475      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
2476  {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
2477  {'0': 0.0, '1': 0.1111111111111111, '2': 0.148...

                                 betweenness_centrality  \
0     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
1     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
2     {'0': 0.0, '1': 0.16666666666666666, '2': 0.26...
3     {'0': 0.0, '1': 0.1111111111111111, '2': 0.194...
4                        {'0': 0.0, '1': 0.5, '2': 0.0}
...                                                 ...
2473  {'0': 0.0, '1': 0.3333333333333333, '2': 0.333...
2474  {'0': 0.0, '1': 0.1, '2': 0.17777777777777778,...
2475                     {'0': 0.0, '1': 0.5, '2': 0.0}
2476  {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
2477  {'0': 0.0, '1': 0.1111111111111111, '2': 0.194...

                                                 degree  transitivity  \
0      {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
1      {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
2     {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
3     {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
4                              {'0': 1, '1': 2, '2': 1}             0
...                                                 ...           ...
2473                   {'0': 1, '1': 2, '2': 2, '3': 1}             0
2474  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
2475                           {'0': 1, '1': 2, '2': 1}             0
2476           {'0': 1, '1': 2, '2': 2, '3': 2, '4': 1}             0
2477  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0

                                   shortest_path_length  \
0     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
1     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
2     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
3     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
4     {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
...                                                 ...
2473  {'0': {'0': 0, '1': 1, '2': 2, '3': 3}, '1': {...
2474  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
2475  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
2476  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}...
2477  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...

                                 eigenvector_centrality  \
0     {'0': 1.800995096925549e-13, '1': 1.6641194695...
1     {'0': 1.800995096925549e-13, '1': 1.6641194695...
2     {'0': 1.0604381234672364e-15, '1': 9.968118360...
3     {'0': 4.9537045204812465e-22, '1': 4.805093384...
4     {'0': 2.9780340102584615e-06, '1': 0.002441987...
...                                                 ...
2473  {'0': 9.080114753549862e-09, '1': 7.9178600650...
2474  {'0': 4.7953579458884704e-24, '1': 4.685064713...
2475  {'0': 2.9780340102584615e-06, '1': 0.002441987...
2476  {'0': 3.63361523133218e-11, '1': 3.28115455389...
2477  {'0': 4.9537045204812465e-22, '1': 4.805093384...

                                               pagerank  \
0     {'0': 0.0607158048829909, '1': 0.1123242344582...
1     {'0': 0.0607158048829909, '1': 0.1123242344582...
2     {'0': 0.04762025246977224, '1': 0.088097655544...
3     {'0': 0.02752799757437422, '1': 0.050927050510...
4     {'0': 0.1844167633067642, '1': 0.3411716203526...
...                                                 ...
2473  {'0': 0.11615558155321364, '1': 0.214887855207...
2474  {'0': 0.02387941414459939, '1': 0.044177071115...
2475  {'0': 0.1844167633067642, '1': 0.3411716203526...
2476  {'0': 0.08118382772690558, '1': 0.150189066098...
2477  {'0': 0.02752799757437422, '1': 0.050927050510...

                                                   hubs  \
0     {'0': 0.2728707247957101, '1': 0.4998027534058...
1     {'0': 3.076518268243052, '1': -0.8203610172578...
2     {'0': 0.003662750431850028, '1': -0.0492964440...
3     {'0': 0.08838357055224336, '1': -0.16403482098...
4     {'0': -0.24842600625369726, '1': 1.24842600625...
...                                                 ...
2473  {'0': -1.0455164855127932, '1': 14.96654397650...
2474  {'0': 3.725375583276068, '1': 0.03974619333343...
2475  {'0': -0.02378980495572733, '1': 1.02378980495...
2476  {'0': 0.9181483663192503, '1': 0.0006321782436...
2477  {'0': -0.6438255070947084, '1': 3.901169625264...

                                            authorities  \
0     {'0': -0.0, '1': 0.2728707247957101, '2': 0.49...
1     {'0': -0.0, '1': 3.076518268243052, '2': -0.82...
2     {'0': 0.0, '1': 0.003662750431850028, '2': -0....
3     {'0': -0.0, '1': 0.08838357055224336, '2': -0....
4     {'0': 0.0, '1': -0.24842600625369726, '2': 1.2...
...                                                 ...
2473  {'0': -0.0, '1': -1.0455164855127932, '2': 14....
2474  {'0': -0.0, '1': 3.725375583276067, '2': 0.039...
2475  {'0': -0.0, '1': -0.02378980495572733, '2': 1....
2476  {'0': 0.0, '1': 0.9181483663192503, '2': 0.000...
2477  {'0': -0.0, '1': -0.6438255070947084, '2': 3.9...

                                                 k_core   density  \
0      {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667
1      {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667
2     {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.142857
3     {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.100000
4                              {'0': 1, '1': 1, '2': 1}  0.333333
...                                                 ...       ...
2473                   {'0': 1, '1': 1, '2': 1, '3': 1}  0.250000
2474  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.090909
2475                           {'0': 1, '1': 1, '2': 1}  0.333333
2476           {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}  0.200000
2477  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.100000

             label
0          correct
1          correct
2          correct
3     Optimization
4          correct
...            ...
2473  Optimization
2474  Optimization
2475  Optimization
2476  Optimization
2477  Optimization

[2478 rows x 13 columns]
Maximum number of rows for padding: 24
Total combined data points from code structure directory: 5320
               0    1     2              3     4     5     6  \
0     InputLayer  0.0  None           LSTM  None  None  None
1     InputLayer  0.0  None          Dense  None  None  None
2     InputLayer  0.0  None        Masking  None  None  None
3     InputLayer  0.0  None         Conv2D  None  None  None
4     InputLayer  0.0  None         Conv2D  None  None  None
...          ...  ...   ...            ...   ...   ...   ...
5315  InputLayer  0.0  None         Conv2D  None  None  None
5316  InputLayer  0.0  None          Dense  None  None  None
5317  InputLayer  0.0  None  Normalization  None  None  None
5318  InputLayer  0.0  None           LSTM  None  None  None
5319  InputLayer  0.0  None        Masking  None  None  None

                        7                   8      9  ...  279  280  281  282  \
0           [None, 10, 5]       [None, 10, 8]  False  ...  NaN  NaN  NaN  NaN
1             [None, 128]          [None, 32]  False  ...  NaN  NaN  NaN  NaN
2        [None, 32, 1000]    [None, 32, 1000]  False  ...  NaN  NaN  NaN  NaN
3       [None, 64, 64, 3]  [None, 64, 64, 64]  False  ...  NaN  NaN  NaN  NaN
4     [None, 100, 100, 1]  [None, 98, 98, 32]  False  ...  NaN  NaN  NaN  NaN
...                   ...                 ...    ...  ...  ...  ...  ...  ...
5315    [None, 64, 64, 3]  [None, 62, 62, 32]  False  ...  NaN  NaN  NaN  NaN
5316            [None, 2]           [None, 4]  False  ...  NaN  NaN  NaN  NaN
5317      [None, 160, 48]     [None, 160, 48]  False  ...  NaN  NaN  NaN  NaN
5318        [None, 5, 18]       [None, 5, 50]  False  ...  NaN  NaN  NaN  NaN
5319        [None, 4, 99]       [None, 4, 99]  False  ...  NaN  NaN  NaN  NaN

     283 284 285 286 287         label
0    NaN NaN NaN NaN NaN       correct
1    NaN NaN NaN NaN NaN       correct
2    NaN NaN NaN NaN NaN       correct
3    NaN NaN NaN NaN NaN       correct
4    NaN NaN NaN NaN NaN       correct
...   ..  ..  ..  ..  ..           ...
5315 NaN NaN NaN NaN NaN  Optimization
5316 NaN NaN NaN NaN NaN       correct
5317 NaN NaN NaN NaN NaN       correct
5318 NaN NaN NaN NaN NaN  Optimization
5319 NaN NaN NaN NaN NaN       correct

[5320 rows x 289 columns]

Label 4: Loss

In [5]:
def json_files_to_df(directory, label_keyword):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                with open(file_path, 'r') as f:
                    json_data = json.load(f)
                    data.append(json_data)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    df = pd.DataFrame(data)
    return df

# Embedding
df_Loss_embedding = json_files_to_df(directory_embedding, 'Loss')
df_correct_embedding = json_files_to_df(directory_embedding, 'correct')
df_Loss_embedding['label'] = 'Loss'
df_correct_embedding['label'] = 'correct'
min_count_embedding = min(len(df_Loss_embedding), len(df_correct_embedding))
df_Loss_embedding = df_Loss_embedding.sample(n=min_count_embedding, random_state=1)
df_correct_embedding = df_correct_embedding.sample(n=min_count_embedding, random_state=1)
df_combined_embedding = pd.concat([df_Loss_embedding, df_correct_embedding])
df_combined_embedding = df_combined_embedding.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Loss_embedding)} Loss files from embedding directory')
print(f'Selected {len(df_correct_embedding)} correct files from embedding directory')
print(f'Total combined data points from embedding directory: {len(df_combined_embedding)}')
df_combined_embedding.to_json('combined_embedding.json', orient='records')
print(df_combined_embedding)
labeled_Loss_embedding = df_combined_embedding.copy()
labeled_Loss_embedding.to_csv('labeled_Loss_embedding.csv', index=False)

# Graph
df_Loss_graph = json_files_to_df(directory_graph, 'Loss')
df_correct_graph = json_files_to_df(directory_graph, 'correct')
df_Loss_graph['label'] = 'Loss'
df_correct_graph['label'] = 'correct'
min_count_graph = min(len(df_Loss_graph), len(df_correct_graph))
df_Loss_graph = df_Loss_graph.sample(n=min_count_graph, random_state=1)
df_correct_graph = df_correct_graph.sample(n=min_count_graph, random_state=1)
df_combined_graph = pd.concat([df_Loss_graph, df_correct_graph])
df_combined_graph = df_combined_graph.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Loss_graph)} Loss files from graph directory')
print(f'Selected {len(df_correct_graph)} correct files from graph directory')
print(f'Total combined data points from graph directory: {len(df_combined_graph)}')
df_combined_graph.to_json('combined_graph.json', orient='records')
print(df_combined_graph)
labeled_Loss_graph = df_combined_graph.copy()
labeled_Loss_graph.to_csv('labeled_Loss_graph.csv', index=False)

# Code Structure
def read_json(file_path):
    with open(file_path, 'r') as f:
        json_data = [json.loads(line) for line in f]
    df = pd.DataFrame(json_data)
    return df

def determine_max_rows(directory, label_keyword):
    max_rows = 0;
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                max_rows = max(max_rows, len(df))
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return max_rows

def process_directory(directory, label_keyword, max_rows):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                current_rows = len(df)
                if current_rows < max_rows:
                    padding = pd.DataFrame([{}] * (max_rows - current_rows))
                    df = pd.concat([df, padding], ignore_index=True)
                df_flat = df.values.flatten() 
                data.append(df_flat)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return pd.DataFrame(data)

max_rows_codeStructure = determine_max_rows(directory_codeStructure, 'Loss')
max_rows_codeStructure = max(max_rows_codeStructure, determine_max_rows(directory_codeStructure, 'correct'))
print(f'Maximum number of rows for padding: {max_rows_codeStructure}')
df_Loss_codeStructure = process_directory(directory_codeStructure, 'Loss', max_rows_codeStructure)
df_correct_codeStructure = process_directory(directory_codeStructure, 'correct', max_rows_codeStructure)
df_Loss_codeStructure['label'] = 'Loss'
df_correct_codeStructure['label'] = 'correct'

df_combined_codeStructure = pd.concat([df_Loss_codeStructure, df_correct_codeStructure])
df_combined_codeStructure = df_combined_codeStructure.sample(frac=1, random_state=1).reset_index(drop=True)

print(f'Total combined data points from code structure directory: {len(df_combined_codeStructure)}')
df_combined_codeStructure.to_json('labeled_Loss_codeStructure.json', orient='records')
print(df_combined_codeStructure)
labeled_Loss_codeStructure_padded = df_combined_codeStructure.copy()
labeled_Loss_codeStructure_padded.to_csv('labeled_Loss_codeStructure_padding.csv', index=False)

Selected 2147 Loss files from embedding directory
Selected 2147 correct files from embedding directory
Total combined data points from embedding directory: 4294
                       model_file  \
0        3888_61553510_correct.h5
1        1956_50481178_correct.h5
2     3050_68716219_Loss_buggy.h5
3     1712_31556268_Loss_buggy.h5
4        3710_52782432_correct.h5
...                           ...
4289      139_66952606_correct.h5
4290      768_70406438_correct.h5
4291   958_48934338_Loss_buggy.h5
4292     2254_64522751_correct.h5
4293  4094_70777445_Loss_buggy.h5

                                              embedding    label
0     [0.16860774159431458, 0.26869839429855347, 0.1...  correct
1     [0.1863144040107727, 0.26561617851257324, 0.10...  correct
2     [0.1786985695362091, 0.22215530276298523, 0.09...     Loss
3     [0.17462360858917236, 0.24255846440792084, 0.0...     Loss
4     [0.17078107595443726, 0.26121094822883606, 0.1...  correct
...                                                 ...      ...
4289  [0.16779743134975433, 0.24546700716018677, 0.1...  correct
4290  [0.1664772629737854, 0.2449311465024948, 0.096...  correct
4291  [0.17616623640060425, 0.2509119212627411, 0.08...     Loss
4292  [0.15345042943954468, 0.22860024869441986, 0.0...  correct
4293  [0.1823151409626007, 0.2448534220457077, 0.117...     Loss

[4294 rows x 3 columns]
Selected 2147 Loss files from graph directory
Selected 2147 correct files from graph directory
Total combined data points from graph directory: 4294
                                      degree_centrality  \
0                                  {'0': 1.0, '1': 1.0}
1     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
2     {'0': 0.25, '1': 0.5, '2': 0.5, '3': 0.5, '4':...
3     {'0': 0.3333333333333333, '1': 0.6666666666666...
4     {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
...                                                 ...
4289  {'0': 0.25, '1': 0.5, '2': 0.5, '3': 0.5, '4':...
4290  {'0': 0.125, '1': 0.25, '2': 0.25, '3': 0.25, ...
4291                     {'0': 0.5, '1': 1.0, '2': 0.5}
4292  {'0': 0.125, '1': 0.25, '2': 0.25, '3': 0.25, ...
4293  {'0': 0.3333333333333333, '1': 0.6666666666666...

                                   closeness_centrality  \
0                                  {'0': 0.0, '1': 1.0}
1     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
2     {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
3     {'0': 0.0, '1': 0.3333333333333333, '2': 0.444...
4     {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
...                                                 ...
4289  {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
4290  {'0': 0.0, '1': 0.125, '2': 0.1666666666666666...
4291      {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
4292  {'0': 0.0, '1': 0.125, '2': 0.1666666666666666...
4293  {'0': 0.0, '1': 0.3333333333333333, '2': 0.444...

                                 betweenness_centrality  \
0                                  {'0': 0.0, '1': 0.0}
1     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
2     {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
3     {'0': 0.0, '1': 0.3333333333333333, '2': 0.333...
4     {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
...                                                 ...
4289  {'0': 0.0, '1': 0.25, '2': 0.3333333333333333,...
4290  {'0': 0.0, '1': 0.125, '2': 0.2142857142857142...
4291                     {'0': 0.0, '1': 0.5, '2': 0.0}
4292  {'0': 0.0, '1': 0.125, '2': 0.2142857142857142...
4293  {'0': 0.0, '1': 0.3333333333333333, '2': 0.333...

                                                 degree  transitivity  \
0                                      {'0': 1, '1': 1}             0
1      {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
2              {'0': 1, '1': 2, '2': 2, '3': 2, '4': 1}             0
3                      {'0': 1, '1': 2, '2': 2, '3': 1}             0
4      {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
...                                                 ...           ...
4289           {'0': 1, '1': 2, '2': 2, '3': 2, '4': 1}             0
4290  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
4291                           {'0': 1, '1': 2, '2': 1}             0
4292  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': ...             0
4293                   {'0': 1, '1': 2, '2': 2, '3': 1}             0

                                   shortest_path_length  \
0                {'0': {'0': 0, '1': 1}, '1': {'1': 0}}
1     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
2     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}...
3     {'0': {'0': 0, '1': 1, '2': 2, '3': 3}, '1': {...
4     {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
...                                                 ...
4289  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}...
4290  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
4291  {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
4292  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
4293  {'0': {'0': 0, '1': 1, '2': 2, '3': 3}, '1': {...

                                 eigenvector_centrality  \
0     {'0': 0.001410435832630306, '1': 0.99999900533...
1     {'0': 1.800995096925549e-13, '1': 1.6641194695...
2     {'0': 3.63361523133218e-11, '1': 3.28115455389...
3     {'0': 9.080114753549862e-09, '1': 7.9178600650...
4     {'0': 1.800995096925549e-13, '1': 1.6641194695...
...                                                 ...
4289  {'0': 3.63361523133218e-11, '1': 3.28115455389...
4290  {'0': 5.659155616038475e-20, '1': 5.4441077026...
4291  {'0': 2.9780340102584615e-06, '1': 0.002441987...
4292  {'0': 5.659155616038475e-20, '1': 5.4441077026...
4293  {'0': 9.080114753549862e-09, '1': 7.9178600650...

                                               pagerank  \
0     {'0': 0.3508773619358619, '1': 0.649122638064138}
1     {'0': 0.0607158048829909, '1': 0.1123242344582...
2     {'0': 0.08118382772690558, '1': 0.150189066098...
3     {'0': 0.11615558155321364, '1': 0.214887855207...
4     {'0': 0.0607158048829909, '1': 0.1123242344582...
...                                                 ...
4289  {'0': 0.08118382772690558, '1': 0.150189066098...
4290  {'0': 0.0322868281045965, '1': 0.0597302537620...
4291  {'0': 0.1844167633067642, '1': 0.3411716203526...
4292  {'0': 0.0322868281045965, '1': 0.0597302537620...
4293  {'0': 0.11615558155321364, '1': 0.214887855207...

                                                   hubs  \
0                                 {'0': 1.0, '1': -0.0}
1     {'0': 0.8024487265321344, '1': 0.3854909899008...
2     {'0': -6.069946141861019, '1': 3.2267128731750...
3     {'0': -0.6954649357264188, '1': -1.12021244436...
4     {'0': 0.27382458396480364, '1': 0.712079942920...
...                                                 ...
4289  {'0': -0.12750755709700648, '1': -0.3019968986...
4290  {'0': 0.15450925653067082, '1': 0.030431704752...
4291  {'0': 0.9591262461140319, '1': 0.0408737538859...
4292  {'0': -0.09311102399312965, '1': 0.97116481225...
4293  {'0': 0.33926841165635413, '1': -0.01780523496...

                                            authorities  \
0                                 {'0': -0.0, '1': 1.0}
1     {'0': 0.0, '1': 0.8024487265321344, '2': 0.385...
2     {'0': 0.0, '1': -6.069946141861019, '2': 3.226...
3     {'0': 0.0, '1': -0.6954649357264188, '2': -1.1...
4     {'0': -0.0, '1': 0.27382458396480364, '2': 0.7...
...                                                 ...
4289  {'0': 0.0, '1': -0.12750755709700648, '2': -0....
4290  {'0': -0.0, '1': 0.15450925653067082, '2': 0.0...
4291  {'0': 0.0, '1': 0.9591262461140319, '2': 0.040...
4292  {'0': -0.0, '1': -0.09311102399312966, '2': 0....
4293  {'0': -0.0, '1': 0.33926841165635413, '2': -0....

                                                 k_core   density    label
0                                      {'0': 1, '1': 1}  0.500000  correct
1      {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  correct
2              {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}  0.200000     Loss
3                      {'0': 1, '1': 1, '2': 1, '3': 1}  0.250000     Loss
4      {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  correct
...                                                 ...       ...      ...
4289           {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}  0.200000  correct
4290  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.111111  correct
4291                           {'0': 1, '1': 1, '2': 1}  0.333333     Loss
4292  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': ...  0.111111  correct
4293                   {'0': 1, '1': 1, '2': 1, '3': 1}  0.250000     Loss

[4294 rows x 13 columns]
Maximum number of rows for padding: 24
Total combined data points from code structure directory: 6228
               0    1     2              3     4     5     6                7  \
0     InputLayer  0.0  None           LSTM  None  None  None    [None, 5, 18]
1     InputLayer  0.0  None        Masking  None  None  None    [None, 4, 99]
2     InputLayer  0.0  None  Bidirectional  None  None  None  [None, None, 3]
3     InputLayer  0.0  None      Embedding  None  None  None      [None, 500]
4     InputLayer  0.0  None          Dense  None  None  None        [None, 1]
...          ...  ...   ...            ...   ...   ...   ...              ...
6223  InputLayer  0.0  None      Embedding  None  None  None      [None, 300]
6224  InputLayer  0.0  None          Dense  None  None  None        [None, 1]
6225  InputLayer  0.0  None           LSTM  None  None  None    [None, 14, 4]
6226  InputLayer  0.0  None          Dense  None  None  None        [None, 2]
6227  InputLayer  0.0  None      SimpleRNN  None  None  None  [None, 50, 128]

                     8      9  ...  279  280  281  282 283 284 285 286 287  \
0        [None, 5, 50]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
1        [None, 4, 99]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
2           [None, 64]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
3     [None, 500, 128]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
4           [None, 50]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
...                ...    ...  ...  ...  ...  ...  ...  ..  ..  ..  ..  ..
6223  [None, 300, 100]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
6224        [None, 50]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
6225    [None, 14, 64]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
6226         [None, 4]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN
6227       [None, 128]  False  ...  NaN  NaN  NaN  NaN NaN NaN NaN NaN NaN

        label
0        Loss
1        Loss
2     correct
3     correct
4     correct
...       ...
6223     Loss
6224  correct
6225  correct
6226     Loss
6227  correct

[6228 rows x 289 columns]

Label 5: Activation

In [6]:
def json_files_to_df(directory, label_keyword):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                with open(file_path, 'r') as f:
                    json_data = json.load(f)
                    data.append(json_data)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    df = pd.DataFrame(data)
    return df

# Embedding
df_Activation_embedding = json_files_to_df(directory_embedding, 'Activation')
df_correct_embedding = json_files_to_df(directory_embedding, 'correct')
df_Activation_embedding['label'] = 'Activation'
df_correct_embedding['label'] = 'correct'
min_count_embedding = min(len(df_Activation_embedding), len(df_correct_embedding))
df_Activation_embedding = df_Activation_embedding.sample(n=min_count_embedding, random_state=1)
df_correct_embedding = df_correct_embedding.sample(n=min_count_embedding, random_state=1)
df_combined_embedding = pd.concat([df_Activation_embedding, df_correct_embedding])
df_combined_embedding = df_combined_embedding.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Activation_embedding)} Activation files from embedding directory')
print(f'Selected {len(df_correct_embedding)} correct files from embedding directory')
print(f'Total combined data points from embedding directory: {len(df_combined_embedding)}')
df_combined_embedding.to_json('combined_embedding.json', orient='records')
print(df_combined_embedding)
labeled_Activation_embedding = df_combined_embedding.copy()
labeled_Activation_embedding.to_csv('labeled_Activation_embedding.csv', index=False)

# Graph
df_Activation_graph = json_files_to_df(directory_graph, 'Activation')
df_correct_graph = json_files_to_df(directory_graph, 'correct')
df_Activation_graph['label'] = 'Activation'
df_correct_graph['label'] = 'correct'
min_count_graph = min(len(df_Activation_graph), len(df_correct_graph))
df_Activation_graph = df_Activation_graph.sample(n=min_count_graph, random_state=1)
df_correct_graph = df_correct_graph.sample(n=min_count_graph, random_state=1)
df_combined_graph = pd.concat([df_Activation_graph, df_correct_graph])
df_combined_graph = df_combined_graph.sample(frac=1, random_state=1).reset_index(drop=True)
print(f'Selected {len(df_Activation_graph)} Activation files from graph directory')
print(f'Selected {len(df_correct_graph)} correct files from graph directory')
print(f'Total combined data points from graph directory: {len(df_combined_graph)}')
df_combined_graph.to_json('combined_graph.json', orient='records')
print(df_combined_graph)
labeled_Activation_graph = df_combined_graph.copy()
labeled_Activation_graph.to_csv('labeled_Activation_graph.csv', index=False)

# Code Structure
def read_json(file_path):
    with open(file_path, 'r') as f:
        json_data = [json.loads(line) for line in f]
    df = pd.DataFrame(json_data)
    return df

def determine_max_rows(directory, label_keyword):
    max_rows = 0;
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                max_rows = max(max_rows, len(df))
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return max_rows

def process_directory(directory, label_keyword, max_rows):
    data = []
    for filename in os.listdir(directory):
        if label_keyword in filename:
            file_path = os.path.join(directory, filename)
            try:
                df = read_json(file_path)
                current_rows = len(df)
                if current_rows < max_rows:
                    padding = pd.DataFrame([{}] * (max_rows - current_rows))
                    df = pd.concat([df, padding], ignore_index=True)
                df_flat = df.values.flatten() 
                data.append(df_flat)
            except json.JSONDecodeError as e:
                print(f'Error decoding JSON from file {file_path}: {e}')
            except Exception as e:
                print(f'Unexpected error reading file {file_path}: {e}')
    return pd.DataFrame(data)

max_rows_codeStructure = determine_max_rows(directory_codeStructure, 'Activation')
max_rows_codeStructure = max(max_rows_codeStructure, determine_max_rows(directory_codeStructure, 'correct'))
print(f'Maximum number of rows for padding: {max_rows_codeStructure}')
df_Activation_codeStructure = process_directory(directory_codeStructure, 'Activation', max_rows_codeStructure)
df_correct_codeStructure = process_directory(directory_codeStructure, 'correct', max_rows_codeStructure)
df_Activation_codeStructure['label'] = 'Activation'
df_correct_codeStructure['label'] = 'correct'

df_combined_codeStructure = pd.concat([df_Activation_codeStructure, df_correct_codeStructure])
df_combined_codeStructure = df_combined_codeStructure.sample(frac=1, random_state=1).reset_index(drop=True)

print(f'Total combined data points from code structure directory: {len(df_combined_codeStructure)}')
df_combined_codeStructure.to_json('labeled_Activation_codeStructure.json', orient='records')
print(df_combined_codeStructure)
labeled_Activation_codeStructure_padded = df_combined_codeStructure.copy()
labeled_Activation_codeStructure_padded.to_csv('labeled_Activation_codeStructure_padding.csv', index=False)

Selected 311 Activation files from embedding directory
Selected 311 correct files from embedding directory
Total combined data points from embedding directory: 622
                            model_file  \
0             2068_46642627_correct.h5
1             2348_66840108_correct.h5
2    6362_50481178_Activation_buggy.h5
3             1611_34311586_correct.h5
4    4664_73148058_Activation_buggy.h5
..                                 ...
617  2008_67590787_Activation_buggy.h5
618  4658_73148058_Activation_buggy.h5
619  2096_67590787_Activation_buggy.h5
620  4715_73148058_Activation_buggy.h5
621  4785_73148058_Activation_buggy.h5

                                             embedding       label
0    [0.18680569529533386, 0.2601884603500366, 0.09...     correct
1    [0.18907904624938965, 0.25772982835769653, 0.0...     correct
2    [0.18763253092765808, 0.26183465123176575, 0.0...  Activation
3    [0.1823645532131195, 0.24697138369083405, 0.09...     correct
4    [0.1570563018321991, 0.25130629539489746, 0.10...  Activation
..                                                 ...         ...
617  [0.16840700805187225, 0.24638810753822327, 0.1...  Activation
618  [0.15730509161949158, 0.2372576892375946, 0.10...  Activation
619  [0.17669689655303955, 0.2459408938884735, 0.12...  Activation
620  [0.1616230607032776, 0.25994253158569336, 0.10...  Activation
621  [0.15800701081752777, 0.25335705280303955, 0.1...  Activation

[622 rows x 3 columns]
Selected 311 Activation files from graph directory
Selected 311 correct files from graph directory
Total combined data points from graph directory: 622
                                     degree_centrality  \
0                       {'0': 0.5, '1': 1.0, '2': 0.5}
1                       {'0': 0.5, '1': 1.0, '2': 0.5}
2    {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
3                       {'0': 0.5, '1': 1.0, '2': 0.5}
4    {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
..                                                 ...
617  {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
618  {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
619  {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
620  {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...
621  {'0': 0.2, '1': 0.4, '2': 0.4, '3': 0.4, '4': ...

                                  closeness_centrality  \
0        {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
1        {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
2    {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
3        {'0': 0.0, '1': 0.5, '2': 0.6666666666666666}
4    {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
..                                                 ...
617  {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
618  {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
619  {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
620  {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...
621  {'0': 0.0, '1': 0.2, '2': 0.26666666666666666,...

                                betweenness_centrality  \
0                       {'0': 0.0, '1': 0.5, '2': 0.0}
1                       {'0': 0.0, '1': 0.5, '2': 0.0}
2    {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
3                       {'0': 0.0, '1': 0.5, '2': 0.0}
4    {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
..                                                 ...
617  {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
618  {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
619  {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
620  {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...
621  {'0': 0.0, '1': 0.2, '2': 0.30000000000000004,...

                                               degree  transitivity  \
0                            {'0': 1, '1': 2, '2': 1}             0
1                            {'0': 1, '1': 2, '2': 1}             0
2    {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
3                            {'0': 1, '1': 2, '2': 1}             0
4    {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
..                                                ...           ...
617  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
618  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
619  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
620  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0
621  {'0': 1, '1': 2, '2': 2, '3': 2, '4': 2, '5': 1}             0

                                  shortest_path_length  \
0    {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
1    {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
2    {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
3    {'0': {'0': 0, '1': 1, '2': 2}, '1': {'1': 0, ...
4    {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
..                                                 ...
617  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
618  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
619  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
620  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...
621  {'0': {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4,...

                                eigenvector_centrality  \
0    {'0': 2.9780340102584615e-06, '1': 0.002441987...
1    {'0': 2.9780340102584615e-06, '1': 0.002441987...
2    {'0': 1.800995096925549e-13, '1': 1.6641194695...
3    {'0': 2.9780340102584615e-06, '1': 0.002441987...
4    {'0': 1.800995096925549e-13, '1': 1.6641194695...
..                                                 ...
617  {'0': 1.800995096925549e-13, '1': 1.6641194695...
618  {'0': 1.800995096925549e-13, '1': 1.6641194695...
619  {'0': 1.800995096925549e-13, '1': 1.6641194695...
620  {'0': 1.800995096925549e-13, '1': 1.6641194695...
621  {'0': 1.800995096925549e-13, '1': 1.6641194695...

                                              pagerank  \
0    {'0': 0.1844167633067642, '1': 0.3411716203526...
1    {'0': 0.1844167633067642, '1': 0.3411716203526...
2    {'0': 0.0607158048829909, '1': 0.1123242344582...
3    {'0': 0.1844167633067642, '1': 0.3411716203526...
4    {'0': 0.0607158048829909, '1': 0.1123242344582...
..                                                 ...
617  {'0': 0.0607158048829909, '1': 0.1123242344582...
618  {'0': 0.0607158048829909, '1': 0.1123242344582...
619  {'0': 0.0607158048829909, '1': 0.1123242344582...
620  {'0': 0.0607158048829909, '1': 0.1123242344582...
621  {'0': 0.0607158048829909, '1': 0.1123242344582...

                                                  hubs  \
0    {'0': -1.2035915149637395, '1': 2.203591514963...
1    {'0': 2.7884209022869517, '1': -1.788420902286...
2    {'0': 0.011851212569998664, '1': -0.2519070323...
3    {'0': 0.5842173109079413, '1': 0.4157826890920...
4    {'0': 0.0, '1': -0.033779873376751486, '2': 0....
..                                                 ...
617  {'0': 0.050157778255188926, '1': -0.1448956078...
618  {'0': 0.8659621770707719, '1': 0.0165142595253...
619  {'0': 0.1192236588820541, '1': -0.099685082278...
620  {'0': 0.028690720573733283, '1': 1.22252837801...
621  {'0': 0.0, '1': -0.01861616357379404, '2': -2....

                                           authorities  \
0    {'0': -0.0, '1': -1.2035915149637395, '2': 2.2...
1    {'0': 0.0, '1': 2.7884209022869517, '2': -1.78...
2    {'0': 0.0, '1': 0.011851212569998664, '2': -0....
3    {'0': 0.0, '1': 0.5842173109079413, '2': 0.415...
4    {'0': 0.0, '1': 0.0, '2': -0.03377987337675148...
..                                                 ...
617  {'0': -0.0, '1': 0.050157778255188926, '2': -0...
618  {'0': 0.0, '1': 0.8659621770707719, '2': 0.016...
619  {'0': -0.0, '1': 0.1192236588820541, '2': -0.0...
620  {'0': -0.0, '1': 0.028690720573733283, '2': 1....
621  {'0': 0.0, '1': 0.0, '2': -0.01861616357379404...

                                               k_core   density       label
0                            {'0': 1, '1': 1, '2': 1}  0.333333     correct
1                            {'0': 1, '1': 1, '2': 1}  0.333333     correct
2    {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation
3                            {'0': 1, '1': 1, '2': 1}  0.333333     correct
4    {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation
..                                                ...       ...         ...
617  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation
618  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation
619  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation
620  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation
621  {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}  0.166667  Activation

[622 rows x 13 columns]
Maximum number of rows for padding: 24
Total combined data points from code structure directory: 4392
               0    1     2          3     4               5               6  \
0     InputLayer  0.0  None  Embedding  None            None            None
1     InputLayer  0.0  None       LSTM  None            None            None
2     InputLayer  0.0  None      Dense  None            None            None
3     InputLayer  0.0  None    Masking  None            None            None
4     InputLayer  0.0  None       LSTM  None            None            None
...          ...  ...   ...        ...   ...             ...             ...
4387  InputLayer  0.0  None    Masking  None  [None, 300, 7]  [None, 300, 7]
4388  InputLayer  0.0  None    Masking  None            None            None
4389  InputLayer  0.0  None      Dense  None            None            None
4390  InputLayer  0.0  None      Dense  None            None            None
4391  InputLayer  0.0  None       LSTM  None            None            None

                  7                  8      9  ...   279   280   281   282  \
0     [None, 3, 10]  [None, 3, 10, 64]  False  ...   NaN   NaN   NaN   NaN
1     [None, 5, 18]      [None, 5, 50]  False  ...   NaN   NaN   NaN   NaN
2        [None, 12]         [None, 32]  False  ...   NaN   NaN   NaN   NaN
3     [None, 4, 99]      [None, 4, 99]  False  ...   NaN   NaN   NaN   NaN
4     [None, 10, 5]      [None, 10, 8]  False  ...   NaN   NaN   NaN   NaN
...             ...                ...    ...  ...   ...   ...   ...   ...
4387          False               None   None  ...  None  None  None  None
4388  [None, 4, 99]      [None, 4, 99]  False  ...   NaN   NaN   NaN   NaN
4389    [None, 128]         [None, 32]  False  ...   NaN   NaN   NaN   NaN
4390      [None, 2]        [None, 196]  False  ...   NaN   NaN   NaN   NaN
4391   [None, 3, 1]      [None, 3, 64]  False  ...   NaN   NaN   NaN   NaN

     283 284 285 286 287       label
0    NaN NaN NaN NaN NaN     correct
1    NaN NaN NaN NaN NaN     correct
2    NaN NaN NaN NaN NaN     correct
3    NaN NaN NaN NaN NaN     correct
4    NaN NaN NaN NaN NaN     correct
...   ..  ..  ..  ..  ..         ...
4387 NaN NaN NaN NaN NaN     correct
4388 NaN NaN NaN NaN NaN     correct
4389 NaN NaN NaN NaN NaN     correct
4390 NaN NaN NaN NaN NaN     correct
4391 NaN NaN NaN NaN NaN  Activation

[4392 rows x 289 columns]